@extends('layouts.app')
@push('style')
    @livewireStyles()
@endpush
@push('script')
    @livewireScripts()
@endpush
@section('content')
<body>
    <header>
        @include('partials.navbar')
    </header>
    <main>
        @include('partials.hero')
        @include('partials.project')
        @include('partials.contact')
        
    </main>
</body>
@endsection